### ISSUE TITLE
Did you create the app?

### ISSUE THREAD

**Issue by karl-police** [RokasKil/WO-Mic-Client#1]
Did you create the WO Mic App for iOS? I tried finding a repository.

I am aware about certain tools like the idevice library that allows to let someone change their iOS's device's location. But I am unfamiliar with Microphone things.

**Comment by RokasKil** [comment]
No, this is just a third party desktop client for the app (only tested with android) made as a uni project.

**Comment by karl-police** [comment]
> No, this is just a third party desktop client for the app (only tested with android) made as a uni project.

do you might know how the actual app works?
